### DISCUSSION TITLE
Weird entry in JSON RPC config file `jsonrpc2.yml`

### DISCUSSION THREAD

**Discussion by filipre** [AsamK/signal-cli#772] [Q&A] [answered]
Hi

I'm coming from https://github.com/bbernhard/signal-cli-rest-api/discussions/160#discussioncomment-1451765. There, we assume that every entry in the `jsonrpc2.yml` file lists a mobile phone number but for some reason, when I link my device, the file not only contains my phone number but also some weird entry (I censored some parts of that ID since I don't know what it represents). When I remove it, it gets added automatically again.
```
config:
  "****************":
    tcp_port: 6000
    fifo_pathname: /tmp/sigsocket0
  +rLEX*********H+YxaoQxo**********6ru1oUpIgY=:
    tcp_port: 6001
    fifo_pathname: /tmp/sigsocket1
```

Any idea what it represents and whether we need to read data from there? Does `signal-cli` create that file? What do you do with that file?

**Update**: I now know that this id represents a group that I have. There exists a file with the same name inside the `group-cache` folder. However, I still don't understand how it gets there.
