### ISSUE TITLE
Daemon (TCP) multi-account mode - Account does not exist

### ISSUE THREAD

**Issue by digitalbodhi** [AsamK/signal-cli#1448]
**Problem:** I have an issue where signal-cli is not picking up a registered account (it is the only registered account) in daemon mode.

**Context:**

- I'm using the docker build [signal-cli-jre v0-12-8-1](https://gitlab.com/packaging/signal-cli/container_registry/2701805?after=v0-12-7-3)
- I have a python program that connects to the docker instance using the daemon tcp option in multi-account mode, sending jsonrpc messages.
- This used to work fine in v0.11.7, but given the version deprecation that recently happened, I needed to upgrade to v0.12.8.  
- I have registered the phone directly on the container and validated that I can send and receive messages using signal-cli commands directly on the container
- I am using /root/.local/share/signal-cli/data to store the keys and validated that it contains the accounts.json and other files

**Issue**
_Scenario 1_

These are the arguments I pass to daemon mode (via the docker compose "command"):
`-vv --trust-new-identities always daemon --tcp 0.0.0.0:7583`

```
signal-cli  | 2024-02-06T11:02:17.875Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
signal-cli  | 2024-02-06T11:02:17.887Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.8
signal-cli  | 2024-02-06T11:02:17.988Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.36.1
signal-cli  | 2024-02-06T11:02:17.989Z [main] TRACE org.asamk.signal.manager.Manager - Expected exception when checking libsignal-client: Deserialization failure in zkgroup
signal-cli  | 2024-02-06T11:02:17.989Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
signal-cli  | 2024-02-06T11:02:18.309Z [main] TRACE o.a.s.manager.storage.SignalAccount - Opening account file
signal-cli  | 2024-02-06T11:02:18.311Z [main] TRACE o.a.s.manager.storage.SignalAccount - Loading account file
signal-cli  | 2024-02-06T11:02:18.339Z [main] TRACE o.a.s.manager.storage.SignalAccount - Migrating legacy parts of account file
signal-cli  | 2024-02-06T11:02:18.340Z [main] WARN  o.a.s.manager.MultiAccountManager - Ignoring +1xxxxxxxxxx: User is not registered. (NotRegisteredException)
signal-cli  | 2024-02-06T11:02:18.342Z [main] INFO  o.a.signal.commands.DaemonCommand - Starting daemon in multi-account mode
signal-cli  | 2024-02-06T11:02:18.351Z [main] INFO  org.asamk.signal.util.IOUtils - Listening on socket: /0.0.0.0:7583

```
However, I'm unable to send/receive any messages (as you'd expect from the output above):

Sending this:
`{"jsonrpc": "2.0", "method": "updateProfile", "params": {"account": "+1xxxxxxxxx", "name": "FL", "givenName": "First", "familyName": "Last"}, "id": 11} 
`
Results in this:
```
{'error': {'code': -32602,
           'data': None,
           'message': 'Specified account does not exist'},
 'id': 11,
 'jsonrpc': '2.0'} 
```
_Scenario 2_

Noticing this, I tried specifying the account, and changed the args I pass to docker compose:
`-vv --trust-new-identities always -a +1xxxxxxxxx daemon --tcp 0.0.0.0:7583`

However when doing this, I get the following output and signal-cli exits:

```
signal-cli  | 2024-02-06T11:04:50.165Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_RUNTIME_DIR not set, falling back to temp dir
signal-cli  | 2024-02-06T11:04:50.179Z [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.8
signal-cli  | 2024-02-06T11:04:50.251Z [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.36.1
signal-cli  | 2024-02-06T11:04:50.252Z [main] TRACE org.asamk.signal.manager.Manager - Expected exception when checking libsignal-client: Deserialization failure in zkgroup
signal-cli  | 2024-02-06T11:04:50.252Z [main] DEBUG org.asamk.signal.util.IOUtils - XDG_DATA_HOME not set, falling back to home dir
signal-cli  | 2024-02-06T11:04:50.475Z [main] TRACE org.asamk.signal.App - Loading account file for +1xxxxxxxxx
signal-cli  | User +1xxxxxxxxx is not registered.
signal-cli exited with code 1
```
_Scenario 3_

Now, whats really odd (and clues me in to a potential bug) is that if i go into the container (reverting back to the daemon multi-account config), and I run, side-by-side on a different port, the daemon works as expected and I can send and receive messages no problem:
`signal-cli -vv --trust-new-identities always -a +1xxxxxxxxx daemon --tcp 0.0.0.0:7584`

**Summary:**

- These last two commands (not multi-account mode) are equivalent, but for whatever reason signal-cli is behaving vastly different depending on when it is executed within the container vs. using the docker compose command.
- The multi-account mode does not pick up the account at all, for whatever reason

**Reference**
Here's my docker compose:

```
version: "3"
services:
  signal-cli:
    container_name: signal-cli
    image: registry.gitlab.com/packaging/signal-cli/signal-cli-jre:latest
    command: -vv --trust-new-identities always daemon --tcp 0.0.0.0:7583
    ports:
      - "7583:7583"
      - "7584:7584"
    volumes:
      - "/localpath/signal-cli:/root/.local/share/signal-cli/data"
    tmpfs:
      - "/tmp:exec"
```

Steps to reproduce:
- pull the docker image: `docker compose up`
- get a shell on the container: `docker exec -u 0 -it signal-cli /bin/bash`
- within shell, perform steps to register account and send message to validate registration
- validate that /root/.local/share/signal-cli/data contains the accounts.json and associated data
- run the `signal-cli -vv --trust-new-identities always -a +1xxxxxxxxx daemon --tcp 0.0.0.0:7584`
- attempt to interface with the container on port 7583 and validate that messages can't be sent (scenario 2)
- attempt to interface with the container on port 7584 and validate that messages can be sent (scenario 3)
- modify docker compose to add in the account to the command string `command: -vv --trust-new-identities always -a +1xxxxxxxxxx daemon --tcp 0.0.0.0:7583`
- attempt to start the container (scenario 1) and it fails

**Comment by fvonberg** [comment]
I have an similiar issue, also need to update from v0.11 to v0.12:

My compose looks like this:
```
signal-cli:
    image: registry.gitlab.com/packaging/signal-cli/signal-cli-jre:latest
    restart: 'always'
    command: daemon --tcp 0.0.0.0:7583
    ports:
      - "7583:7583"
    volumes:
      - ./services/signal-cli-config:/var/lib/signal-cli
    tmpfs:
      - "/tmp:exec"
```

My container crashes with the message: `Failed to read local accounts list`
I also tried with v0.12.2 -> same issue.

**Comment by AsamK** [comment]
@digitalbodhi sounds like some issue with the docker container, maybe different mounted paths or different env variables. What's the content of $XDG_DATA_HOME and $HOME for both types of invocations.

@fvonberg can you provide a verbose log with `-v`?

**Comment by digitalbodhi** [comment]
@AsamK 
$HOME=/root 
$XDG_DATA_HOME=<null>

However, as a result of playing around with the env variables so that when I specified $XDG_DATA_HOME, the behavior was the same as when I didn't specify it, I saw permissions denied errors.

```
signal-cli  | 2024-02-08T00:18:28.798Z [main] TRACE org.asamk.signal.App - Loading account file for +1xxxxxxxxxx
signal-cli  | Error loading state file for user +1xxxxxxxxxx: /var/lib/signal-cli/data/accounts.json (Permission denied) (FileNotFoundException)
signal-cli  | java.io.FileNotFoundException: /var/lib/signal-cli/data/accounts.json (Permission denied)

```

And if I make all files in the signal-cli/data directory readable, writeable (and for directories, executable) by all, both daemon multi-account and daemon account modes work as expected (i.e., scenario 1 and scenario 2 work).  

What is strange is that on version v0.12.8, the signal-cli/data files that are created (i.e., I didn't migrate from an old version) are given permissions that causes permission denied errors for daemon mode for subsequent server startups.  **In other words, either the files should be created with more lax permissions, or the load process for the daemon is perhaps happening under the wrong user.**

This Scenario 1 config now works as expected after adjusting permissions to the signal-cli files to be chmod a+rwx:
```
version: "3"
services:
  signal-cli:
    container_name: signal-cli
    image: registry.gitlab.com/packaging/signal-cli/signal-cli-jre:latest
    command: -vv --trust-new-identities always daemon --tcp 0.0.0.0:7583
    environment:
      - HOME=/root
      - XDG_DATA_HOME=/var/lib
    ports:
      - "7583:7583"
    volumes:
      - "/localpathto/signal-cli:/var/lib/signal-cli"
    tmpfs:
      - "/tmp:exec"

```
